"""add google OAth 2.0 via openid

Revision ID: 3a8b00c19ea1
Revises: e566ee96e4ce
Create Date: 2026-03-10 18:40:09.817528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8b00c19ea1'
down_revision: Union[str, Sequence[str], None] = 'e566ee96e4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    authprovider = sa.Enum('LOCAL', 'GOOGLE', 'HYBRID', name='authprovider')
    authprovider.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', authprovider, nullable=False, server_default='LOCAL'))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('picture_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'picture_url')
    op.drop_column('users', 'username')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')

    sa.Enum(name='authprovider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
