"""add authentication via google OAuth 2.0

Revision ID: e566ee96e4ce
Revises: 8a6b31f71ef4
Create Date: 2026-03-09 20:52:58.414012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e566ee96e4ce'
down_revision: Union[str, Sequence[str], None] = '8a6b31f71ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
